-- Expand signup countries to the current ISO 3166-1 assigned set (249 entries).
-- Sources:
--   https://www.iso.org/iso-3166-country-codes.html
--   https://unstats.un.org/unsd/methodology/m49/
--
-- CountryUniqueID=1 remains the United States so existing State_Ref and users
-- foreign keys remain valid. All other IDs are frozen in ISO alpha-2 order.

SET @has_iso_alpha2 = (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'Country_Ref'
    AND COLUMN_NAME = 'ISOAlpha2'
);
SET @sql = IF(
  @has_iso_alpha2 = 0,
  'ALTER TABLE `Country_Ref` ADD COLUMN `ISOAlpha2` char(2) DEFAULT NULL AFTER `CountryUniqueID`',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

INSERT INTO `Country_Ref` (`CountryUniqueID`, `ISOAlpha2`, `Country`) VALUES
(2, 'AD', 'Andorra'),
(3, 'AE', 'United Arab Emirates'),
(4, 'AF', 'Afghanistan'),
(5, 'AG', 'Antigua and Barbuda'),
(6, 'AI', 'Anguilla'),
(7, 'AL', 'Albania'),
(8, 'AM', 'Armenia'),
(9, 'AO', 'Angola'),
(10, 'AQ', 'Antarctica'),
(11, 'AR', 'Argentina'),
(12, 'AS', 'American Samoa'),
(13, 'AT', 'Austria'),
(14, 'AU', 'Australia'),
(15, 'AW', 'Aruba'),
(16, 'AX', 'Åland Islands'),
(17, 'AZ', 'Azerbaijan'),
(18, 'BA', 'Bosnia and Herzegovina'),
(19, 'BB', 'Barbados'),
(20, 'BD', 'Bangladesh'),
(21, 'BE', 'Belgium'),
(22, 'BF', 'Burkina Faso'),
(23, 'BG', 'Bulgaria'),
(24, 'BH', 'Bahrain'),
(25, 'BI', 'Burundi'),
(26, 'BJ', 'Benin'),
(27, 'BL', 'Saint Barthélemy'),
(28, 'BM', 'Bermuda'),
(29, 'BN', 'Brunei Darussalam'),
(30, 'BO', 'Bolivia (Plurinational State of)'),
(31, 'BQ', 'Bonaire, Sint Eustatius and Saba'),
(32, 'BR', 'Brazil'),
(33, 'BS', 'Bahamas'),
(34, 'BT', 'Bhutan'),
(35, 'BV', 'Bouvet Island'),
(36, 'BW', 'Botswana'),
(37, 'BY', 'Belarus'),
(38, 'BZ', 'Belize'),
(39, 'CA', 'Canada'),
(40, 'CC', 'Cocos (Keeling) Islands'),
(41, 'CD', 'Democratic Republic of the Congo'),
(42, 'CF', 'Central African Republic'),
(43, 'CG', 'Congo'),
(44, 'CH', 'Switzerland'),
(45, 'CI', 'Côte d’Ivoire'),
(46, 'CK', 'Cook Islands'),
(47, 'CL', 'Chile'),
(48, 'CM', 'Cameroon'),
(49, 'CN', 'China'),
(50, 'CO', 'Colombia'),
(51, 'CR', 'Costa Rica'),
(52, 'CU', 'Cuba'),
(53, 'CV', 'Cabo Verde'),
(54, 'CW', 'Curaçao'),
(55, 'CX', 'Christmas Island'),
(56, 'CY', 'Cyprus'),
(57, 'CZ', 'Czechia'),
(58, 'DE', 'Germany'),
(59, 'DJ', 'Djibouti'),
(60, 'DK', 'Denmark'),
(61, 'DM', 'Dominica'),
(62, 'DO', 'Dominican Republic'),
(63, 'DZ', 'Algeria'),
(64, 'EC', 'Ecuador'),
(65, 'EE', 'Estonia'),
(66, 'EG', 'Egypt'),
(67, 'EH', 'Western Sahara'),
(68, 'ER', 'Eritrea'),
(69, 'ES', 'Spain'),
(70, 'ET', 'Ethiopia'),
(71, 'FI', 'Finland'),
(72, 'FJ', 'Fiji'),
(73, 'FK', 'Falkland Islands (Malvinas)'),
(74, 'FM', 'Micronesia (Federated States of)'),
(75, 'FO', 'Faroe Islands'),
(76, 'FR', 'France'),
(77, 'GA', 'Gabon'),
(78, 'GB', 'United Kingdom of Great Britain and Northern Ireland'),
(79, 'GD', 'Grenada'),
(80, 'GE', 'Georgia'),
(81, 'GF', 'French Guiana'),
(82, 'GG', 'Guernsey'),
(83, 'GH', 'Ghana'),
(84, 'GI', 'Gibraltar'),
(85, 'GL', 'Greenland'),
(86, 'GM', 'Gambia'),
(87, 'GN', 'Guinea'),
(88, 'GP', 'Guadeloupe'),
(89, 'GQ', 'Equatorial Guinea'),
(90, 'GR', 'Greece'),
(91, 'GS', 'South Georgia and the South Sandwich Islands'),
(92, 'GT', 'Guatemala'),
(93, 'GU', 'Guam'),
(94, 'GW', 'Guinea-Bissau'),
(95, 'GY', 'Guyana'),
(96, 'HK', 'China, Hong Kong Special Administrative Region'),
(97, 'HM', 'Heard Island and McDonald Islands'),
(98, 'HN', 'Honduras'),
(99, 'HR', 'Croatia'),
(100, 'HT', 'Haiti'),
(101, 'HU', 'Hungary'),
(102, 'ID', 'Indonesia'),
(103, 'IE', 'Ireland'),
(104, 'IL', 'Israel'),
(105, 'IM', 'Isle of Man'),
(106, 'IN', 'India'),
(107, 'IO', 'British Indian Ocean Territory'),
(108, 'IQ', 'Iraq'),
(109, 'IR', 'Iran (Islamic Republic of)'),
(110, 'IS', 'Iceland'),
(111, 'IT', 'Italy'),
(112, 'JE', 'Jersey'),
(113, 'JM', 'Jamaica'),
(114, 'JO', 'Jordan'),
(115, 'JP', 'Japan'),
(116, 'KE', 'Kenya'),
(117, 'KG', 'Kyrgyzstan'),
(118, 'KH', 'Cambodia'),
(119, 'KI', 'Kiribati'),
(120, 'KM', 'Comoros'),
(121, 'KN', 'Saint Kitts and Nevis'),
(122, 'KP', 'Democratic People''s Republic of Korea'),
(123, 'KR', 'Republic of Korea'),
(124, 'KW', 'Kuwait'),
(125, 'KY', 'Cayman Islands'),
(126, 'KZ', 'Kazakhstan'),
(127, 'LA', 'Lao People''s Democratic Republic'),
(128, 'LB', 'Lebanon'),
(129, 'LC', 'Saint Lucia'),
(130, 'LI', 'Liechtenstein'),
(131, 'LK', 'Sri Lanka'),
(132, 'LR', 'Liberia'),
(133, 'LS', 'Lesotho'),
(134, 'LT', 'Lithuania'),
(135, 'LU', 'Luxembourg'),
(136, 'LV', 'Latvia'),
(137, 'LY', 'Libya'),
(138, 'MA', 'Morocco'),
(139, 'MC', 'Monaco'),
(140, 'MD', 'Republic of Moldova'),
(141, 'ME', 'Montenegro'),
(142, 'MF', 'Saint Martin (French Part)'),
(143, 'MG', 'Madagascar'),
(144, 'MH', 'Marshall Islands'),
(145, 'MK', 'North Macedonia'),
(146, 'ML', 'Mali'),
(147, 'MM', 'Myanmar'),
(148, 'MN', 'Mongolia'),
(149, 'MO', 'China, Macao Special Administrative Region'),
(150, 'MP', 'Northern Mariana Islands'),
(151, 'MQ', 'Martinique'),
(152, 'MR', 'Mauritania'),
(153, 'MS', 'Montserrat'),
(154, 'MT', 'Malta'),
(155, 'MU', 'Mauritius'),
(156, 'MV', 'Maldives'),
(157, 'MW', 'Malawi'),
(158, 'MX', 'Mexico'),
(159, 'MY', 'Malaysia'),
(160, 'MZ', 'Mozambique'),
(161, 'NA', 'Namibia'),
(162, 'NC', 'New Caledonia'),
(163, 'NE', 'Niger'),
(164, 'NF', 'Norfolk Island'),
(165, 'NG', 'Nigeria'),
(166, 'NI', 'Nicaragua'),
(167, 'NL', 'Netherlands (Kingdom of the)'),
(168, 'NO', 'Norway'),
(169, 'NP', 'Nepal'),
(170, 'NR', 'Nauru'),
(171, 'NU', 'Niue'),
(172, 'NZ', 'New Zealand'),
(173, 'OM', 'Oman'),
(174, 'PA', 'Panama'),
(175, 'PE', 'Peru'),
(176, 'PF', 'French Polynesia'),
(177, 'PG', 'Papua New Guinea'),
(178, 'PH', 'Philippines'),
(179, 'PK', 'Pakistan'),
(180, 'PL', 'Poland'),
(181, 'PM', 'Saint Pierre and Miquelon'),
(182, 'PN', 'Pitcairn'),
(183, 'PR', 'Puerto Rico'),
(184, 'PS', 'State of Palestine'),
(185, 'PT', 'Portugal'),
(186, 'PW', 'Palau'),
(187, 'PY', 'Paraguay'),
(188, 'QA', 'Qatar'),
(189, 'RE', 'Réunion'),
(190, 'RO', 'Romania'),
(191, 'RS', 'Serbia'),
(192, 'RU', 'Russian Federation'),
(193, 'RW', 'Rwanda'),
(194, 'SA', 'Saudi Arabia'),
(195, 'SB', 'Solomon Islands'),
(196, 'SC', 'Seychelles'),
(197, 'SD', 'Sudan'),
(198, 'SE', 'Sweden'),
(199, 'SG', 'Singapore'),
(200, 'SH', 'Saint Helena'),
(201, 'SI', 'Slovenia'),
(202, 'SJ', 'Svalbard and Jan Mayen Islands'),
(203, 'SK', 'Slovakia'),
(204, 'SL', 'Sierra Leone'),
(205, 'SM', 'San Marino'),
(206, 'SN', 'Senegal'),
(207, 'SO', 'Somalia'),
(208, 'SR', 'Suriname'),
(209, 'SS', 'South Sudan'),
(210, 'ST', 'Sao Tome and Principe'),
(211, 'SV', 'El Salvador'),
(212, 'SX', 'Sint Maarten (Dutch part)'),
(213, 'SY', 'Syrian Arab Republic'),
(214, 'SZ', 'Eswatini'),
(215, 'TC', 'Turks and Caicos Islands'),
(216, 'TD', 'Chad'),
(217, 'TF', 'French Southern Territories'),
(218, 'TG', 'Togo'),
(219, 'TH', 'Thailand'),
(220, 'TJ', 'Tajikistan'),
(221, 'TK', 'Tokelau'),
(222, 'TL', 'Timor-Leste'),
(223, 'TM', 'Turkmenistan'),
(224, 'TN', 'Tunisia'),
(225, 'TO', 'Tonga'),
(226, 'TR', 'Türkiye'),
(227, 'TT', 'Trinidad and Tobago'),
(228, 'TV', 'Tuvalu'),
(229, 'TW', 'Taiwan, Province of China'),
(230, 'TZ', 'United Republic of Tanzania'),
(231, 'UA', 'Ukraine'),
(232, 'UG', 'Uganda'),
(233, 'UM', 'United States Minor Outlying Islands'),
(1, 'US', 'United States of America'),
(234, 'UY', 'Uruguay'),
(235, 'UZ', 'Uzbekistan'),
(236, 'VA', 'Holy See'),
(237, 'VC', 'Saint Vincent and the Grenadines'),
(238, 'VE', 'Venezuela (Bolivarian Republic of)'),
(239, 'VG', 'British Virgin Islands'),
(240, 'VI', 'United States Virgin Islands'),
(241, 'VN', 'Viet Nam'),
(242, 'VU', 'Vanuatu'),
(243, 'WF', 'Wallis and Futuna Islands'),
(244, 'WS', 'Samoa'),
(245, 'YE', 'Yemen'),
(246, 'YT', 'Mayotte'),
(247, 'ZA', 'South Africa'),
(248, 'ZM', 'Zambia'),
(249, 'ZW', 'Zimbabwe')
ON DUPLICATE KEY UPDATE
  `ISOAlpha2` = VALUES(`ISOAlpha2`),
  `Country` = VALUES(`Country`);

SET @has_unique_iso_alpha2 = (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'Country_Ref'
    AND COLUMN_NAME = 'ISOAlpha2'
    AND NON_UNIQUE = 0
);
SET @sql = IF(
  @has_unique_iso_alpha2 = 0,
  'ALTER TABLE `Country_Ref` ADD UNIQUE KEY `Unique_Country_ISOAlpha2` (`ISOAlpha2`)',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

