-- Preserve the percentage values users actually submit for active detail rows.
--
-- Deployment order:
--   1. Back up the database.
--   2. Run this migration.
--   3. Deploy the application code that writes four-decimal percentages.
--
-- Existing integer values are widened without changing their value. This
-- migration intentionally does not guess or repair historical totals such as
-- 98 or 99 because the original submitted decimal values are unavailable.
-- Active detail primary keys are also changed to AUTO_INCREMENT so concurrent
-- saves no longer compete for an application-generated MAX(id) + 1 value.

ALTER TABLE `FragmentsColorDetails`
    MODIFY COLUMN `FragmentColor_UniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `FragColorPercent` DECIMAL(7,4) NOT NULL
        COMMENT 'Percent for that color type';

ALTER TABLE `FragmentsFormDetails`
    MODIFY COLUMN `FragForm_UniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `FragFormPercent` DECIMAL(7,4) NOT NULL;

ALTER TABLE `FragmentsOpacityDetails`
    MODIFY COLUMN `FragOpacity_UniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `FragOpacityPercent` DECIMAL(7,4) NOT NULL;

ALTER TABLE `FragmentsPurposes`
    MODIFY COLUMN `FragPurposeUniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `Percent_Purpose` DECIMAL(7,4) NOT NULL
        COMMENT 'Percent of each purpose type in sample';

ALTER TABLE `FragmentsPolymerDetails`
    MODIFY COLUMN `Percentage` DECIMAL(7,4) NULL DEFAULT NULL;

ALTER TABLE `MicroplasticsColorDetails`
    MODIFY COLUMN `MicroColor_UniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `MicroColorPercent` DECIMAL(7,4) NOT NULL;

ALTER TABLE `MicroplasticsOpacityDetails`
    MODIFY COLUMN `MicroOpacityUniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `MicroOpacityPercent` DECIMAL(7,4) NOT NULL;

ALTER TABLE `MicroplasticsSizeDetails`
    MODIFY COLUMN `MicroplasticsSize_UniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `MicroSizePercent` DECIMAL(7,4) NOT NULL;

ALTER TABLE `MicroplasticsFormDetails`
    MODIFY COLUMN `MicroForm_UniqueID` INT(11) NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `MicroShape_Percent` DECIMAL(7,4) NULL DEFAULT NULL,
    MODIFY COLUMN `MicroTexture_Percent` DECIMAL(7,4) NULL DEFAULT NULL;

ALTER TABLE `MicroplasticsPolymerDetails`
    MODIFY COLUMN `Percentage` DECIMAL(7,4) NULL DEFAULT NULL;

-- Post-migration schema check. Every row should report a decimal type with
-- enough room for 100.0000 (precision >= 7 and scale >= 4).
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND (
      (TABLE_NAME = 'FragmentsColorDetails' AND COLUMN_NAME = 'FragColorPercent')
      OR (TABLE_NAME = 'FragmentsFormDetails' AND COLUMN_NAME = 'FragFormPercent')
      OR (TABLE_NAME = 'FragmentsOpacityDetails' AND COLUMN_NAME = 'FragOpacityPercent')
      OR (TABLE_NAME = 'FragmentsPurposes' AND COLUMN_NAME = 'Percent_Purpose')
      OR (TABLE_NAME = 'FragmentsPolymerDetails' AND COLUMN_NAME = 'Percentage')
      OR (TABLE_NAME = 'MicroplasticsColorDetails' AND COLUMN_NAME = 'MicroColorPercent')
      OR (TABLE_NAME = 'MicroplasticsOpacityDetails' AND COLUMN_NAME = 'MicroOpacityPercent')
      OR (TABLE_NAME = 'MicroplasticsSizeDetails' AND COLUMN_NAME = 'MicroSizePercent')
      OR (TABLE_NAME = 'MicroplasticsFormDetails' AND COLUMN_NAME IN ('MicroShape_Percent', 'MicroTexture_Percent'))
      OR (TABLE_NAME = 'MicroplasticsPolymerDetails' AND COLUMN_NAME = 'Percentage')
  )
ORDER BY TABLE_NAME, COLUMN_NAME;

-- Active detail primary keys should now be generated by the database rather
-- than by SELECT MAX(id) + 1 in concurrent requests.
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND (
      (TABLE_NAME = 'FragmentsColorDetails' AND COLUMN_NAME = 'FragmentColor_UniqueID')
      OR (TABLE_NAME = 'FragmentsFormDetails' AND COLUMN_NAME = 'FragForm_UniqueID')
      OR (TABLE_NAME = 'FragmentsOpacityDetails' AND COLUMN_NAME = 'FragOpacity_UniqueID')
      OR (TABLE_NAME = 'FragmentsPurposes' AND COLUMN_NAME = 'FragPurposeUniqueID')
      OR (TABLE_NAME = 'FragmentsPolymerDetails' AND COLUMN_NAME = 'FragPolymerUniqueID')
      OR (TABLE_NAME = 'MicroplasticsColorDetails' AND COLUMN_NAME = 'MicroColor_UniqueID')
      OR (TABLE_NAME = 'MicroplasticsOpacityDetails' AND COLUMN_NAME = 'MicroOpacityUniqueID')
      OR (TABLE_NAME = 'MicroplasticsSizeDetails' AND COLUMN_NAME = 'MicroplasticsSize_UniqueID')
      OR (TABLE_NAME = 'MicroplasticsFormDetails' AND COLUMN_NAME = 'MicroForm_UniqueID')
      OR (TABLE_NAME = 'MicroplasticsPolymerDetails' AND COLUMN_NAME = 'MicroPolymerUniqueID')
  )
ORDER BY TABLE_NAME, COLUMN_NAME;
