"""Parse the backup SQL dump (generated by scripts/backup-database.js) into dicts."""
import re

ESCAPES = {'n': '\n', 'r': '\r', 't': '\t', '0': '\0', 'Z': '\x1a',
           "'": "'", '"': '"', '\\': '\\', '%': '\\%', '_': '\\_'}


def parse_values(text, start):
    """Parse tuples after VALUES keyword. Returns (list_of_tuples, end_index)."""
    rows = []
    i = start
    n = len(text)
    cur_val = []
    cur_row = []
    in_str = False
    in_tuple = False
    while i < n:
        c = text[i]
        if in_str:
            if c == '\\' and i + 1 < n:
                cur_val.append(ESCAPES.get(text[i + 1], text[i + 1]))
                i += 2
                continue
            if c == "'":
                if i + 1 < n and text[i + 1] == "'":  # doubled quote
                    cur_val.append("'")
                    i += 2
                    continue
                in_str = False
                cur_val.append("\x00END")  # marker: was a string
                i += 1
                continue
            cur_val.append(c)
            i += 1
            continue
        if not in_tuple:
            if c == '(':
                in_tuple = True
                cur_row = []
                cur_val = []
            elif c == ';':
                return rows, i + 1
            i += 1
            continue
        # inside tuple, outside string
        if c == "'":
            if not ''.join(cur_val).strip():
                cur_val = []  # discard pre-quote whitespace (', ' separators)
            in_str = True
            i += 1
        elif c == ',':
            cur_row.append(finish_val(cur_val))
            cur_val = []
            i += 1
        elif c == ')':
            cur_row.append(finish_val(cur_val))
            rows.append(cur_row)
            in_tuple = False
            i += 1
        else:
            cur_val.append(c)
            i += 1
    raise ValueError('unterminated INSERT')


def finish_val(chars):
    s = ''.join(chars)
    if s.endswith('\x00END'):
        return s[:-4]  # string value (may be empty)
    s = s.strip()
    if s.upper() == 'NULL':
        return None
    try:
        return int(s)
    except ValueError:
        try:
            return float(s)
        except ValueError:
            return s


def load_dump(path):
    text = open(path, encoding='utf-8').read()
    tables = {}
    for m in re.finditer(r'INSERT INTO `([^`]+)` \(([^)]*)\) VALUES', text):
        tname = m.group(1)
        cols = [c.strip().strip('`') for c in m.group(2).split(',')]
        rows, _ = parse_values(text, m.end())
        recs = [dict(zip(cols, r)) for r in rows]
        tables.setdefault(tname, []).extend(recs)
    return tables


if __name__ == '__main__':
    import sys
    t = load_dump(sys.argv[1])
    for name in sorted(t):
        print(f'{name}: {len(t[name])} rows')
